# Generated by Django 2.0.8 on 2019-12-09 07:40

import datetime
from django.db import migrations, models
import purchase.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='制造商料号')),
                ('inner_model', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='公司型号')),
                ('categories', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='类型')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='制造商')),
                ('suppliers', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='供应商')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='单价')),
                ('unit', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='单位')),
                ('currency', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='货币')),
                ('package', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='包装量')),
                ('delivery', models.DateTimeField(default=datetime.datetime.now, verbose_name='交期')),
                ('order_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='订货量')),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='税率')),
                ('remark', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='备注')),
                ('path', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='存放路径')),
                ('picture', models.FileField(null=True, upload_to=purchase.models.upload_to, verbose_name='报价图片')),
            ],
            options={
                'verbose_name': '报价记录',
                'verbose_name_plural': '报价记录',
            },
        ),
    ]
